	
	var customIcons = {
		Bank:{
			icon:Icons/Bank.png
		},
		BusStation:{
			icon:Icons/BusStation.png
		},
		Cafe:{
			icon:Icons/Cafe.png
		},
		Company:{
			icon:Icons/Company.png
		},
		CondominiumComplex:{
			icon:Icons/CondominiumComplex.png
		},
		Gym:{
			icon:Icons/Gym.png
		},
		Hospital:{
			icon:Icons/Hospital.png
		},
		MovieTheater:{
			icon:Icons/MovieTheater.png
		},
		Resort:{
			icon:Icons/Resort.png
		},
		Resturant:{
			icon:Icons/Resturant.png
		},
		Service:{
			icon:Icons/Service.png
		},
		ShoppingMall:{
			icon:Icons/ShoppingMall.png
		},
		Therapist:{
			icon:Icons/Therapist.png
		},
		University:{
			icon:Icons/University.png
		},
		Worship:{
			icon:Icons/Worship2.png
		}
	}